#!/usr/bin/env python3
"""
Create a Eurographics/EuroVis-friendly LaTeX table of venues (token counts + NEW KEYs),
restricted to rows where "Exclude Decision" == "corpus".

Requirements implemented:
1) Filter to ONLY rows with "corpus" under "Exclude Decision" (case-insensitive, trimmed).
2) Group tokens (comma-split) and map each token -> associated NEW KEYs.
3) Output a LaTeX table with columns:
     - Venue (each row as token (count))
     - Papers in Corpus (list of NEW KEYs)
4) First rows (in this exact order): TVCG, CGF, VIS, PacificVis, CHI
   Remaining tokens are collapsed into one row:
     Other: token (NEW KEY, NEW KEY), token (NEW KEY, NEW KEY), ...
   with "Other" tokens listed alphabetically.
5) Save to paperVenues.tex

Note: Counts are computed normally (token occurrences across corpus rows). The “priority”
rows stay at the top regardless of their counts, per your instructions.
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, List, Set, Tuple

import pandas as pd


PRIORITY_TOKENS = ["TVCG", "CGF", "VIS", "PacificVis", "CHI"]
OUTFILE = "paperVenues.tex"


def split_comma_tokens(cell) -> List[str]:
    """Split only on commas; strip whitespace; drop empties."""
    if cell is None or (isinstance(cell, float) and pd.isna(cell)):
        return []
    s = str(cell).strip()
    if not s:
        return []
    return [tok.strip() for tok in s.split(",") if tok.strip()]


def count_tokens_and_map_keys(series: pd.Series, keys: pd.Series) -> Tuple[Counter, Dict[str, Set[str]]]:
    """Count tokens and map token -> set of NEW KEYs."""
    counter: Counter = Counter()
    token_to_keys: Dict[str, Set[str]] = defaultdict(set)

    for cell, key in zip(series, keys):
        if pd.isna(cell) or pd.isna(key):
            continue

        key_str = str(key).strip()
        if not key_str:
            continue

        for tok in split_comma_tokens(cell):
            counter[tok] += 1
            token_to_keys[tok].add(key_str)

    return counter, token_to_keys


def latex_escape(s: str) -> str:
    """Escape LaTeX special characters."""
    repl = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(repl.get(ch, ch) for ch in s)


def make_table(counts: Counter, token_to_keys: Dict[str, Set[str]]) -> str:
    # Prepare “Other” list: all tokens not in PRIORITY_TOKENS, alphabetically
    other_tokens = sorted([t for t in counts.keys() if t not in PRIORITY_TOKENS])

    other_chunks: List[str] = []
    for t in other_tokens:
        keys_sorted = sorted(token_to_keys.get(t, set()))
        keys_str = ", ".join(keys_sorted)
        other_chunks.append(f"{latex_escape(t)} ({latex_escape(keys_str)})")

    other_cell = "Other: " + "; ".join(other_chunks) if other_chunks else "Other:"

    lines: List[str] = []
    lines.append(r"% Auto-generated by script. Include with \input{paperVenues.tex}")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\setlength{\tabcolsep}{6pt}")
    lines.append(r"\renewcommand{\arraystretch}{1.15}")
    lines.append(r"\begin{tabular}{p{0.22\linewidth} p{0.72\linewidth}}")
    lines.append(r"\hline")
    lines.append(r"\textbf{Venue} & \textbf{Papers in Corpus} \\")
    lines.append(r"\hline")

    # Priority rows in the requested order.
    # If a priority token is absent, it is skipped.
    for tok in PRIORITY_TOKENS:
        if tok not in counts:
            continue
        venue_cell = f"{latex_escape(tok)} ({counts[tok]})"
        keys_sorted = sorted(token_to_keys.get(tok, set()))
        keys_str = latex_escape(", ".join(keys_sorted))
        lines.append(f"{venue_cell} & {keys_str} \\\\")

    # Other row (single row)
    lines.append(r"\hline")
    lines.append(f"{latex_escape('Other')} & {other_cell} \\\\")
    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Create a LaTeX table of venues with counts and NEW KEYs (corpus rows only)."
    )
    parser.add_argument("excel_path", help="Path to the Excel file (.xlsx, .xlsm, etc.)")
    parser.add_argument("sheet_name", help="Name of the sheet to read")
    parser.add_argument("column_name", help="Name of the venue column to analyse (tokenized by commas)")
    parser.add_argument(
        "--out",
        default=OUTFILE,
        help=f"Output .tex file (default: {OUTFILE})",
    )
    args = parser.parse_args()

    excel_path = Path(args.excel_path)
    if not excel_path.exists():
        raise FileNotFoundError(f"Excel file not found: {excel_path}")

    df = pd.read_excel(excel_path, sheet_name=args.sheet_name, header=1)

    required_cols = ["Exclude Decision", "NEW KEY", args.column_name]
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise KeyError(f"Missing required column(s): {missing}. Found columns: {list(df.columns)}")

    # Only corpus rows
    mask = df["Exclude Decision"].astype(str).str.strip().str.lower().eq("corpus")
    df = df.loc[mask].copy()

    counts, token_to_keys = count_tokens_and_map_keys(df[args.column_name], df["NEW KEY"])

    # (1) Print grouped tokens from highest -> lowest (ties alphabetical)
    for tok, cnt in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])):
        keys_sorted = sorted(token_to_keys.get(tok, set()))
        print(f"{tok} ({cnt}) : {', '.join(keys_sorted)}")

    # (2) Write LaTeX table
    latex = make_table(counts, token_to_keys)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(latex, encoding="utf-8")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
