"use client";

import Table, { type DataTableColumn } from "./table";

const TABLE_COLUMNS: DataTableColumn[] = [
    {
        id: "AuthorYear",
        label: "Author Year",
        group: "Publications",
        dataKey: "AuthorYear",
        minWidth: 120,
        initialWidth: 200,
        filterType: "text",
    },
    {
        id: "agnostic",
        label: "Agnostic",
        group: "Domain Application",
        dataKey: "Agnostic",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#197650",
    },
    {
        id: "medicine",
        label: "Medicine",
        group: "Domain Application",
        dataKey: "Medicine",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#197344",
    },
    {
        id: "publichealth",
        label: "Public Health",
        group: "Domain Application",
        dataKey: "Public Health",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#197344",
    },
    {
        id: "socialcivic",
        label: "Social/Civic",
        group: "Domain Application",
        dataKey: "Social/Civic",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#197344",
    },
    {
        id: "businessindustry",
        label: "Business/Industry",
        group: "Domain Application",
        dataKey: "Business/Industry",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#197344",
    },
    {
        id: "climate",
        label: "Climate",
        group: "Domain Application",
        dataKey: "Climate",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#197344",
    },
    {
        id: "sciedu",
        label: "Science Education",
        group: "Domain Application",
        dataKey: "Science Education",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#197344",
    },
    {
        id: "Journalism",
        label: "Journalism",
        group: "Domain Application",
        dataKey: "Journalism",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#197344",
    },
    {
        id: "culture",
        label: "Culture/Humanities",
        group: "Domain Application",
        dataKey: "Culture/Humanities",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#FF0000",
    },
    {
        id: "various",
        label: "Various",
        group: "Domain Application",
        dataKey: "Various",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#00FF00",
    },
    {
        id: "chart",
        label: "Chart",
        group: "Features",
        dataKey: "chart",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#0000FF",
    },
    {
        id: "graph",
        label: "Graph",
        group: "Features",
        dataKey: "graph",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#0000FF",
    },
    {
        id: "tree",
        label: "Tree",
        group: "Features",
        dataKey: "Tree",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#0000FF",
    },
    {
        id: "Set",
        label: "Set",
        group: "Features",
        dataKey: "Set",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#0000FF",
    },
    {
        id: "map",
        label: "Map",
        group: "Features",
        dataKey: "Map",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#0000FF",
    },
    {
        id: "pictograph",
        label: "Pictograph",
        group: "Features",
        dataKey: "Pictograph",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#0000FF",
    },
    {
        id: "interactivity",
        label: "Interactivity",
        group: "Features",
        dataKey: "Interactivity",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#0000FF",
    },
    {
        id: "animation",
        label: "Animation",
        group: "Features",
        dataKey: "Animation",
        minWidth: 42,
        initialWidth: 52,
        filterType: "feature",
        color: "#2e7d32",
    },
];

const TABLE_DATA_URL = "/classtable.json";
const TABLE_TITLE = "AV STAR Classification";

export default function TableTestPage() {
    return <Table columns={TABLE_COLUMNS} dataUrl={TABLE_DATA_URL} title={TABLE_TITLE} />;
}
